[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "19"
  NETLIFY_USE_YARN = "false"

# Handle all routes for SPA-style navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200