services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: openfirma-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfirma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openfirma-network

  # Backend API service
  api:
    build: ./backend
    container_name: openfirma-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfirma
    depends_on:
      db:
        condition: service_healthy
    networks:
      - openfirma-network

  # Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: openfirma-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - openfirma-network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: openfirma-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@openfirma.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - openfirma-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  openfirma-network:
    driver: bridge