
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openfirma-api-standalone
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfirma_backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - openfirma-network

  db:
    image: postgres:15-alpine
    container_name: openfirma-db-backend
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfirma_backend
    ports:
      - "5432 :5432"
    volumes:
      - postgres_backend_data:/var/lib/postgresql/data
      - ../infra/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openfirma-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: openfirma-pgadmin-backend
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@openfirma.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_backend_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - openfirma-network


volumes:
  postgres_backend_data:
  pgadmin_backend_data:

networks:
  openfirma-network:
    driver: bridge