
services:
  api:
    build: .
    container_name: openfirma-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfirma
    depends_on:
      - db
    networks:
      - openfirma-network

  db:
    image: postgres:14-alpine
    container_name: openfirma-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfirma
    ports:
      - "5433:5432"
    networks:
      - openfirma-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: openfirma-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@openfirma.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - openfirma-network

networks:
  openfirma-network:
    driver: bridge

volumes:
  postgres_data: