name: Frontend CI

on:
  push:
    branches: [ main, dev, release ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, dev, release ]
    paths:
      - 'frontend/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      - name: Type check
        run: npx tsc --noEmit
        
      - name: Run tests
        run: npm test
        
      - name: Build
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: frontend/.next
          retention-days: 7
