name: Frontend Deploy

on:
  push:
    branches: [ main, release ]  # Removed dev branch
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    # Set environment based on branch
    environment:
      ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    
    defaults:
      run:
        working-directory: frontend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          # Fix: Always use production for Next.js
          export NODE_ENV=production
          echo "Building with NODE_ENV=production"
          npm run build
        
      # - name: Deploy to environment (commented out)
      #   run: |
      #     echo "Deploying to ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }} environment"
      #     # Deployment code placeholder
