name: Frontend Deploy

on:
  push:
    branches: [ main, release ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    # Set environment based on branch
    environment:
      ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    
    defaults:
      run:
        working-directory: frontend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          # Fix: Always use production for Next.js
          export NODE_ENV=production
          echo "Building with NODE_ENV=production"
          npm run build
      
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Deploy to Netlify
        run: |
          # Set site name based on branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            NETLIFY_SITE_NAME="f83f333e-13b8-4ad3-b5b1-0a14c9ff6232"
          else
            NETLIFY_SITE_NAME="your-staging-site-name"
          fi
          
          echo "Deploying to Netlify site: $NETLIFY_SITE_NAME"
          
          # Deploy the site
          netlify deploy --dir=.next --prod --site=$NETLIFY_SITE_NAME --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
