name: Frontend Deploy

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    
    if: github.event_name == 'pull_request' && github.head_ref == 'dev'
    
    environment: pr-preview
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Deploy using nwtgck/actions-netlify which handles Next.js correctly
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './frontend/.next'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "PR #${{ github.event.pull_request.number }} preview"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          alias: ${{ format('pr-{0}', github.event.pull_request.number) }}
          functions-dir: './frontend/.next/server/pages'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: "f83f333e-13b8-4ad3-b5b1-0a14c9ff6232"
        timeout-minutes: 5
