name: Deploy to Production

permissions:
  contents: read
  deployments: write

on:
  # Run when code is actually merged to main
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Build for production
        working-directory: frontend
        run: |
          export NODE_ENV=production
          npm run build
          
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
        
      - name: Deploy to Netlify Production
        working-directory: frontend
        run: |
          # Deploy to production site
          netlify deploy \
            --dir=out \
            --site="f83f333e-13b8-4ad3-b5b1-0a14c9ff6232" \
            --auth="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --message="Production deployment from main branch" \
            --prod \
            --json > deploy_output.json
            
          # Log deployment URL
          DEPLOY_URL=$(cat deploy_output.json | jq -r '.url')
          echo "Deployed to: $DEPLOY_URL"
        id: deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
