name: PR Preview

permissions:
  contents: read
  pull-requests: write
  deployments: write

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'

jobs:
  preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    
    if: github.head_ref == 'dev'
    
    environment: pr-preview
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Build for static export
        working-directory: frontend
        run: |
          # Build Next.js app
          export NODE_ENV=production
          npm run build
          
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
        
      - name: Deploy to Netlify
        working-directory: frontend
        run: |
          # Deploy to Netlify using CLI with out directory
          netlify deploy \
            --dir=out \
            --site="f83f333e-13b8-4ad3-b5b1-0a14c9ff6232" \
            --auth="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --message="PR #${{ github.event.pull_request.number }} preview" \
            --alias="pr-${{ github.event.pull_request.number }}" \
            --json > deploy_output.json
            
          # Extract and output the deploy URL
          cat deploy_output.json
          DEPLOY_URL=$(cat deploy_output.json | jq -r '.deploy_url')
          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        id: deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      
      - name: Comment on PR
        if: steps.deploy.outputs.deploy_url
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deployUrl = '${{ steps.deploy.outputs.deploy_url }}';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 PR Preview deployed to: [Netlify Preview](${deployUrl})`
            });
